from run import grid_search
from torch.optim import Adam

from src.models import BiTULER, TULHOR

if __name__ == "__main__":
    grid_search(
        dataset="foursquare_TKY",
        model_cls=TULHOR,
        n_users=400,
        loc_levels=[2, 3, 4],
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=[100, 200, 300, 400, 500, 600],
        discretization_shape=["hex", "diamond", "square"],
        aggregation_mode="group",
        lr=1e-4,
        n_hidden=1024,
        n_layers=1,
        n_heads=16,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )
    grid_search(
        dataset="foursquare_TKY",
        model_cls=TULHOR,
        n_users=400,
        loc_levels=[2, 3, 4],
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=[100, 200, 300, 400, 500, 600],
        discretization_shape=["hex", "diamond", "square"],
        aggregation_mode="grow",
        grow_factor=[2, 3, 4],
        lr=1e-4,
        n_hidden=1024,
        n_layers=1,
        n_heads=16,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )
    grid_search(
        dataset="foursquare_TKY",
        model_cls=BiTULER,
        n_users=400,
        loc_levels=[2, 3, 4],
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=[100, 200, 300, 400, 500, 600],
        discretization_shape=["hex", "diamond", "square"],
        aggregation_mode="group",
        lr=2e-4,
        n_hidden=1024,
        n_layers=1,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )
    grid_search(
        dataset="foursquare_TKY",
        model_cls=BiTULER,
        n_users=400,
        loc_levels=[2, 3, 4],
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=[100, 200, 300, 400, 500, 600],
        discretization_shape=["hex", "diamond", "square"],
        aggregation_mode="grow",
        grow_factor=[2, 3, 4],
        lr=2e-4,
        n_hidden=1024,
        n_layers=1,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )

    # Baselines
    grid_search(
        dataset="foursquare_TKY",
        model_cls=TULHOR,
        n_users=400,
        loc_levels=1,
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=100,
        discretization_shape="square",
        aggregation_mode="group",
        lr=1e-4,
        n_hidden=1024,
        n_layers=1,
        n_heads=16,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )
    grid_search(
        dataset="foursquare_TKY",
        model_cls=[
            BiTULER,
        ],
        n_users=400,
        loc_levels=1,
        time_levels=1,
        optimizer_cls=Adam,
        discretization_rows=100,
        discretization_shape="square",
        aggregation_mode="group",
        lr=2e-4,
        n_hidden=1024,
        n_layers=1,
        loc_embedding_factor=1,
        time_embedding_factor=1 / 16,
        subsample=5000,
        device="cuda:0",
        log_path="discretization_grid.jsonl",
    )
